import re

import pytest

from fcollections.implementations._definitions._cmems import build_convention


@pytest.mark.parametrize(
    "dataset_id",
    [
        # SEALEVEL_GLO_PHY_L3_MY_008_062
        "cmems_obs-sl_glo_phy-ssh_my_c2-l3-duacs_PT1S",
        "cmems_obs-sl_glo_phy-ssh_my_c2n-l3-duacs_PT1S",
        "cmems_obs-sl_glo_phy-ssh_my_en-l3-duacs_PT1S",
        "cmems_obs-sl_glo_phy-ssh_my_enn-l3-duacs_PT1S",
        "cmems_obs-sl_glo_phy-ssh_my_e1-l3-duacs_PT1S",
        "cmems_obs-sl_glo_phy-ssh_my_e1g-l3-duacs_PT1S",
        "cmems_obs-sl_glo_phy-ssh_my_e2-l3-duacs_PT1S",
        "cmems_obs-sl_glo_phy-ssh_my_g2-l3-duacs_PT1S",
        "cmems_obs-sl_glo_phy-ssh_my_h2a-l3-duacs_PT1S",
        "cmems_obs-sl_glo_phy-ssh_my_h2ag-l3-duacs_PT1S",
        "cmems_obs-sl_glo_phy-ssh_my_h2b-l3-duacs_PT1S",
        "cmems_obs-sl_glo_phy-ssh_my_j1-l3-duacs_PT1S",
        "cmems_obs-sl_glo_phy-ssh_my_j1g-l3-duacs_PT1S",
        "cmems_obs-sl_glo_phy-ssh_my_j1n-l3-duacs_PT1S",
        "cmems_obs-sl_glo_phy-ssh_my_j2-l3-duacs_PT1S",
        "cmems_obs-sl_glo_phy-ssh_my_j2n-l3-duacs_PT1S",
        "cmems_obs-sl_glo_phy-ssh_my_j2g-l3-duacs_PT1S",
        "cmems_obs-sl_glo_phy-ssh_my_j3-l3-duacs_PT1S",
        "cmems_obs-sl_glo_phy-ssh_my_j3n-l3-duacs_PT1S",
        "cmems_obs-sl_glo_phy-ssh_my_j3g-l3-duacs_PT1S-i",
        "cmems_obs-sl_glo_phy-ssh_my_al-l3-duacs_PT1S",
        "cmems_obs-sl_glo_phy-ssh_my_alg-l3-duacs_PT1S",
        "cmems_obs-sl_glo_phy-ssh_my_s3a-l3-duacs_PT1S",
        "cmems_obs-sl_glo_phy-ssh_my_s3b-l3-duacs_PT1S",
        "cmems_obs-sl_glo_phy-ssh_my_s6a-lr-l3-duacs_PT1S",
        "cmems_obs-sl_glo_phy-ssh_my_swon-l3-duacs_PT1S",
        "cmems_obs-sl_glo_phy-ssh_my_swonc-l3-duacs_PT1S",
        "cmems_obs-sl_glo_phy-ssh_my_tp-l3-duacs_PT1S",
        "cmems_obs-sl_glo_phy-ssh_my_tpn-l3-duacs_PT1S",
        # SST_GLO_SST_L3S_NRT_OBSERVATIONS_010_010
        "cmems_obs-sst_glo_phy_l3s_gir_P1D-m",
        "IFREMER-GLOB-SST-L3-NRT-OBS_FULL_TIME_SERIE",
        "cmems_obs-sst_glo_phy_l3s_pir_P1D-m",
        "cmems_obs-sst_glo_phy_l3s_pmw_P1D-m",
        # SEALEVEL_GLO_PHY_L3_NRT_008_044
        "cmems_obs-sl_glo_phy-ssh_nrt_c2n-l3-duacs_PT1S",
        "cmems_obs-sl_glo_phy-ssh_nrt_h2b-l3-duacs_PT1S",
        "cmems_obs-sl_glo_phy-ssh_nrt_h2b-l3-duacs_PT0.2S",
        "cmems_obs-sl_glo_phy-ssh_nrt_j3n-l3-duacs_PT1S",
        "cmems_obs-sl_glo_phy-ssh_nrt_j3n-l3-duacs_PT0.2S",
        "cmems_obs-sl_glo_phy-ssh_nrt_j3g-l3-duacs_PT1S-i",
        "cmems_obs-sl_glo_phy-ssh_nrt_j3g-l3-duacs_PT0.2S-i",
        "cmems_obs-sl_glo_phy-ssh_nrt_al-l3-duacs_PT1S",
        "cmems_obs-sl_glo_phy-ssh_nrt_s3a-l3-duacs_PT1S",
        "cmems_obs-sl_glo_phy-ssh_nrt_s3a-l3-duacs_PT0.2S",
        "cmems_obs-sl_glo_phy-ssh_nrt_s3b-l3-duacs_PT1S",
        "cmems_obs-sl_glo_phy-ssh_nrt_s3b-l3-duacs_PT0.2S",
        "cmems_obs-sl_glo_phy-ssh_nrt_s6a-hr-l3-duacs_PT1S",
        "cmems_obs-sl_glo_phy-ssh_nrt_s6a-hr-l3-duacs_PT0.2S",
        "cmems_obs-sl_glo_phy-ssh_nrt_swon-l3-duacs_PT1S",
        "cmems_obs-sl_glo_phy-ssh_nrt_swon-l3-duacs_PT0.2S",
        # SEALEVEL_GLO_PHY_L4_NRT_008_046
        "cmems_obs-sl_glo_phy-ssh_nrt_demo-allsat-swos-l4-duacs-0.125deg_P1D-i",
        "cmems_obs-sl_glo_phy-ssh_nrt_allsat-l4-duacs-0.125deg_P1D",
        "cmems_obs-sl_glo_phy-ssh_nrt_allsat-l4-duacs-0.25deg_P1D",
        # SEALEVEL_GLO_PHY_L4_MY_008_047
        "cmems_obs-sl_glo_phy-ssh_my_allsat-l4-duacs-0.125deg_P1D",
        "cmems_obs-sl_glo_phy-ssh_my_allsat-demo-l4-duacs-0.125deg_P1D-i",
        "cmems_obs-sl_glo_phy-ssh_my_allsat-l4-duacs-0.125deg_P1M-m",
        # OCEANCOLOUR_GLO_BGC_L3_MY_009_103
        "cmems_obs-oc_glo_bgc-plankton_my_l3-multi-4km_P1D",
        "cmems_obs-oc_glo_bgc-optics_my_l3-multi-4km_P1D",
        "cmems_obs-oc_glo_bgc-plankton_my_l3-olci-300m_P1D",
        "cmems_obs-oc_glo_bgc-plankton_my_l3-olci-4km_P1D",
        "cmems_obs-oc_glo_bgc-reflectance_my_l3-multi-4km_P1D",
        "cmems_obs-oc_glo_bgc-reflectance_my_l3-olci-300m_P1D",
        "cmems_obs-oc_glo_bgc-reflectance_my_l3-olci-4km_P1D",
        "cmems_obs-oc_glo_bgc-transp_my_l3-multi-4km_P1D",
        "cmems_obs-oc_glo_bgc-transp_my_l3-olci-4km_P1D",
        # OCEANCOLOUR_GLO_BGC_L4_MY_009_104
        "cmems_obs-oc_glo_bgc-optics_my_l4-multi-4km_P1M",
        "cmems_obs-oc_glo_bgc-plankton_my_l4-gapfree-multi-4km_P1D",
        "cmems_obs-oc_glo_bgc-plankton_my_l4-multi-4km_P1M",
        "cmems_obs-oc_glo_bgc-plankton_my_l4-multi-climatology-4km_P1D",
        "cmems_obs-oc_glo_bgc-plankton_my_l4-olci-300m_P1M",
        "cmems_obs-oc_glo_bgc-plankton_my_l4-olci-4km_P1M",
        "cmems_obs-oc_glo_bgc-pp_my_l4-multi-4km_P1M",
        "cmems_obs-oc_glo_bgc-reflectance_my_l4-multi-4km_P1M",
        "cmems_obs-oc_glo_bgc-reflectance_my_l4-olci-300m_P1M",
        "cmems_obs-oc_glo_bgc-reflectance_my_l4-olci-4km_P1M",
        "cmems_obs-oc_glo_bgc-transp_my_l4-gapfree-multi-4km_P1D",
        "cmems_obs-oc_glo_bgc-transp_my_l4-multi-4km_P1M",
        "cmems_obs-oc_glo_bgc-transp_my_l4-olci-4km_P1M",
        # OCEANCOLOUR_GLO_BGC_L4_NRT_009_102
        "cmems_obs-oc_glo_bgc-optics_nrt_l4-multi-4km_P1M",
        "cmems_obs-oc_glo_bgc-plankton_nrt_l4-gapfree-multi-4km_P1D",
        "cmems_obs-oc_glo_bgc-plankton_nrt_l4-multi-4km_P1M",
        "cmems_obs-oc_glo_bgc-plankton_nrt_l4-olci-300m_P1M",
        "cmems_obs-oc_glo_bgc-plankton_nrt_l4-olci-4km_P1M",
        "cmems_obs-oc_glo_bgc-pp_nrt_l4-multi-4km_P1M",
        "cmems_obs-oc_glo_bgc-reflectance_nrt_l4-multi-4km_P1M",
        "cmems_obs-oc_glo_bgc-reflectance_nrt_l4-olci-300m_P1M",
        "cmems_obs-oc_glo_bgc-reflectance_nrt_l4-olci-4km_P1M",
        "cmems_obs-oc_glo_bgc-transp_nrt_l4-gapfree-multi-4km_P1D",
        "cmems_obs-oc_glo_bgc-transp_nrt_l4-multi-4km_P1M",
        "cmems_obs-oc_glo_bgc-transp_nrt_l4-olci-4km_P1M",
        # WAVE_GLO_PHY_SWH_L3_NRT_014_001
        "cmems_obs-wave_glo_phy-swh_nrt_cfo-l3_PT1S",
        "cmems_obs-wave_glo_phy-swh_nrt_c2-l3_PT1S",
        "cmems_obs-wave_glo_phy-swh_nrt_h2b-l3_PT1S",
        "cmems_obs-wave_glo_phy-swh_nrt_h2c-l3_PT1S",
        "cmems_obs-wave_glo_phy-swh_nrt_j3-l3_PT1S",
        "cmems_obs-wave_glo_phy-swh_nrt_al-l3_PT1S",
        "cmems_obs-wave_glo_phy-swh_nrt_s3a-l3_PT1S",
        "cmems_obs-wave_glo_phy-swh_nrt_s3b-l3_PT1S",
        "cmems_obs-wave_glo_phy-swh_nrt_s6a-l3_PT1S",
        "cmems_obs-wave_glo_phy-swh_nrt_swon-l3_PT1S",
    ],
)
def test_regex_match(dataset_id: str):
    convention = build_convention()
    actual = convention.regex.match(dataset_id)
    assert actual is not None
